import type { Metadata } from "next";

import "./globals.css";
import QueryProvider from "../components/ui/QueryProvider";


export const metadata: Metadata = {
  title: "AI Search Visibility",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
